### ISSUE TITLE
ASALI installation

### ISSUE THREAD

**Issue by SidraFirdous** [srebughini/ASALI#3]
Dear Stefano,

I have installed Cantera via Conda following the instructions on https://cantera.org/install/conda-install.html

Now, how do I install ASALI? I can't find the program folder for Cantera to replace in the .compile.sh file.

Thanks for the help.

**Comment by srebughini** [comment]
Hi, 

ASALI is strongly bounded to Cantera, so it does not work with the Conda installation.
To compile the Cantera version that you need for ASALI, follow these instructions:

* Install all pre-requites packages with these commands:
`sudo apt-get update`  
`sudo apt-get install git g++ gfortran python scons libboost-dev cython python-dev python-numpy python-numpy-dev python-setuptools cython python3 python3-dev python3-setuptools python3-numpy`  
* Download Cantera from its GitHub repository:    
`git clone https://github.com/Cantera/cantera.git`   
* Type the following commands from the cantera folder:  
`scons build system_sundials=n`   
`sudo scons install`    

Cantera is compiled in `/usr/local/` , which is the *environmental variable* that you need to compile ASALI.

Cheers
